// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/keelerh/omniscience/protos (interfaces: Ingester_IngestServer)

// Package ingester_mocks is a generated GoMock package.
package ingester_mocks

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	empty "github.com/golang/protobuf/ptypes/empty"
	protos "github.com/keelerh/omniscience/protos"
	metadata "google.golang.org/grpc/metadata"
	reflect "reflect"
)

// MockIngester_IngestServer is a mock of Ingester_IngestServer interface
type MockIngester_IngestServer struct {
	ctrl     *gomock.Controller
	recorder *MockIngester_IngestServerMockRecorder
}

// MockIngester_IngestServerMockRecorder is the mock recorder for MockIngester_IngestServer
type MockIngester_IngestServerMockRecorder struct {
	mock *MockIngester_IngestServer
}

// NewMockIngester_IngestServer creates a new mock instance
func NewMockIngester_IngestServer(ctrl *gomock.Controller) *MockIngester_IngestServer {
	mock := &MockIngester_IngestServer{ctrl: ctrl}
	mock.recorder = &MockIngester_IngestServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIngester_IngestServer) EXPECT() *MockIngester_IngestServerMockRecorder {
	return m.recorder
}

// Context mocks base method
func (m *MockIngester_IngestServer) Context() context.Context {
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context
func (mr *MockIngester_IngestServerMockRecorder) Context() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockIngester_IngestServer)(nil).Context))
}

// Recv mocks base method
func (m *MockIngester_IngestServer) Recv() (*protos.Document, error) {
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*protos.Document)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv
func (mr *MockIngester_IngestServerMockRecorder) Recv() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockIngester_IngestServer)(nil).Recv))
}

// RecvMsg mocks base method
func (m *MockIngester_IngestServer) RecvMsg(arg0 interface{}) error {
	ret := m.ctrl.Call(m, "RecvMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg
func (mr *MockIngester_IngestServerMockRecorder) RecvMsg(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockIngester_IngestServer)(nil).RecvMsg), arg0)
}

// SendAndClose mocks base method
func (m *MockIngester_IngestServer) SendAndClose(arg0 *empty.Empty) error {
	ret := m.ctrl.Call(m, "SendAndClose", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendAndClose indicates an expected call of SendAndClose
func (mr *MockIngester_IngestServerMockRecorder) SendAndClose(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendAndClose", reflect.TypeOf((*MockIngester_IngestServer)(nil).SendAndClose), arg0)
}

// SendHeader mocks base method
func (m *MockIngester_IngestServer) SendHeader(arg0 metadata.MD) error {
	ret := m.ctrl.Call(m, "SendHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendHeader indicates an expected call of SendHeader
func (mr *MockIngester_IngestServerMockRecorder) SendHeader(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendHeader", reflect.TypeOf((*MockIngester_IngestServer)(nil).SendHeader), arg0)
}

// SendMsg mocks base method
func (m *MockIngester_IngestServer) SendMsg(arg0 interface{}) error {
	ret := m.ctrl.Call(m, "SendMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg
func (mr *MockIngester_IngestServerMockRecorder) SendMsg(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockIngester_IngestServer)(nil).SendMsg), arg0)
}

// SetHeader mocks base method
func (m *MockIngester_IngestServer) SetHeader(arg0 metadata.MD) error {
	ret := m.ctrl.Call(m, "SetHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetHeader indicates an expected call of SetHeader
func (mr *MockIngester_IngestServerMockRecorder) SetHeader(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHeader", reflect.TypeOf((*MockIngester_IngestServer)(nil).SetHeader), arg0)
}

// SetTrailer mocks base method
func (m *MockIngester_IngestServer) SetTrailer(arg0 metadata.MD) {
	m.ctrl.Call(m, "SetTrailer", arg0)
}

// SetTrailer indicates an expected call of SetTrailer
func (mr *MockIngester_IngestServerMockRecorder) SetTrailer(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTrailer", reflect.TypeOf((*MockIngester_IngestServer)(nil).SetTrailer), arg0)
}
