// Code generated by protoc-gen-go. DO NOT EDIT.
// source: document.proto

/*
Package omniscience is a generated protocol buffer package.

It is generated from these files:
	document.proto
	google_drive.proto
	ingestion.proto
	search.proto

It has these top-level messages:
	Document
	DocumentId
	GetAllDocumentsRequest
	IndexDocumentServiceRequest
	QueryDocumentsRequest
*/
package omniscience

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DocumentService int32

const (
	DocumentService_ALL        DocumentService = 0
	DocumentService_GDRIVE     DocumentService = 1
	DocumentService_JIRA       DocumentService = 2
	DocumentService_CONFLUENCE DocumentService = 3
	DocumentService_GITHUB     DocumentService = 4
)

var DocumentService_name = map[int32]string{
	0: "ALL",
	1: "GDRIVE",
	2: "JIRA",
	3: "CONFLUENCE",
	4: "GITHUB",
}
var DocumentService_value = map[string]int32{
	"ALL":        0,
	"GDRIVE":     1,
	"JIRA":       2,
	"CONFLUENCE": 3,
	"GITHUB":     4,
}

func (x DocumentService) String() string {
	return proto.EnumName(DocumentService_name, int32(x))
}
func (DocumentService) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Document struct {
	Id               *DocumentId                `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name             string                     `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Description      string                     `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	Service          DocumentService            `protobuf:"varint,4,opt,name=service,enum=omniscience.DocumentService" json:"service,omitempty"`
	Content          string                     `protobuf:"bytes,5,opt,name=content" json:"content,omitempty"`
	Url              string                     `protobuf:"bytes,6,opt,name=url" json:"url,omitempty"`
	LastModifiedTime *google_protobuf.Timestamp `protobuf:"bytes,7,opt,name=last_modified_time,json=lastModifiedTime" json:"last_modified_time,omitempty"`
}

func (m *Document) Reset()                    { *m = Document{} }
func (m *Document) String() string            { return proto.CompactTextString(m) }
func (*Document) ProtoMessage()               {}
func (*Document) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Document) GetId() *DocumentId {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Document) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Document) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Document) GetService() DocumentService {
	if m != nil {
		return m.Service
	}
	return DocumentService_ALL
}

func (m *Document) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Document) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Document) GetLastModifiedTime() *google_protobuf.Timestamp {
	if m != nil {
		return m.LastModifiedTime
	}
	return nil
}

type DocumentId struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DocumentId) Reset()                    { *m = DocumentId{} }
func (m *DocumentId) String() string            { return proto.CompactTextString(m) }
func (*DocumentId) ProtoMessage()               {}
func (*DocumentId) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DocumentId) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*Document)(nil), "omniscience.Document")
	proto.RegisterType((*DocumentId)(nil), "omniscience.DocumentId")
	proto.RegisterEnum("omniscience.DocumentService", DocumentService_name, DocumentService_value)
}

func init() { proto.RegisterFile("document.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 316 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x4f, 0x4f, 0xc2, 0x40,
	0x10, 0xc5, 0xed, 0x1f, 0x29, 0x0c, 0x49, 0xdd, 0xcc, 0xc5, 0x0d, 0x21, 0xb1, 0xe1, 0x22, 0xf1,
	0x50, 0x12, 0x4c, 0xbc, 0x23, 0xa0, 0xd4, 0x54, 0x4c, 0x2a, 0x78, 0x25, 0xd0, 0x5d, 0xc8, 0x26,
	0x74, 0x97, 0xb4, 0x8b, 0x5f, 0xc5, 0xaf, 0x6b, 0xba, 0xa5, 0x4a, 0x8c, 0xb7, 0xd9, 0x99, 0x37,
	0x6f, 0xe7, 0xfd, 0xc0, 0x67, 0x2a, 0x3d, 0x66, 0x5c, 0xea, 0xf0, 0x90, 0x2b, 0xad, 0xb0, 0xad,
	0x32, 0x29, 0x8a, 0x54, 0x70, 0x99, 0xf2, 0xce, 0xcd, 0x4e, 0xa9, 0xdd, 0x9e, 0x0f, 0xcc, 0x68,
	0x73, 0xdc, 0x0e, 0xb4, 0xc8, 0x78, 0xa1, 0xd7, 0xd9, 0xa1, 0x52, 0xf7, 0xbe, 0x6c, 0x68, 0x4e,
	0x4e, 0x06, 0x78, 0x0b, 0xb6, 0x60, 0xd4, 0x0a, 0xac, 0x7e, 0x7b, 0x78, 0x1d, 0x9e, 0xf9, 0x84,
	0xb5, 0x24, 0x62, 0x89, 0x2d, 0x18, 0x22, 0xb8, 0x72, 0x9d, 0x71, 0x6a, 0x07, 0x56, 0xbf, 0x95,
	0x98, 0x1a, 0x03, 0x68, 0x33, 0x5e, 0xa4, 0xb9, 0x38, 0x68, 0xa1, 0x24, 0x75, 0xcc, 0xe8, 0xbc,
	0x85, 0x0f, 0xe0, 0x15, 0x3c, 0xff, 0x14, 0x29, 0xa7, 0x6e, 0x60, 0xf5, 0xfd, 0x61, 0xf7, 0xdf,
	0x3f, 0xde, 0x2b, 0x4d, 0x52, 0x8b, 0x91, 0x82, 0x97, 0x2a, 0xa9, 0xb9, 0xd4, 0xf4, 0xd2, 0xb8,
	0xd6, 0x4f, 0x24, 0xe0, 0x1c, 0xf3, 0x3d, 0x6d, 0x98, 0x6e, 0x59, 0xe2, 0x0c, 0x70, 0xbf, 0x2e,
	0xf4, 0x2a, 0x53, 0x4c, 0x6c, 0x05, 0x67, 0xab, 0x32, 0x30, 0xf5, 0x4c, 0xa4, 0x4e, 0x58, 0xd1,
	0x08, 0x6b, 0x1a, 0xe1, 0xa2, 0xa6, 0x91, 0x90, 0x72, 0xeb, 0xf5, 0xb4, 0x54, 0xb6, 0x7b, 0x5d,
	0x80, 0xdf, 0xd4, 0xe8, 0xff, 0xa0, 0x69, 0x95, 0x04, 0xee, 0x62, 0xb8, 0xfa, 0x73, 0x2f, 0x7a,
	0xe0, 0x8c, 0xe2, 0x98, 0x5c, 0x20, 0x40, 0xe3, 0x79, 0x92, 0x44, 0x1f, 0x53, 0x62, 0x61, 0x13,
	0xdc, 0x97, 0x28, 0x19, 0x11, 0x1b, 0x7d, 0x80, 0xf1, 0xdb, 0xfc, 0x29, 0x5e, 0x4e, 0xe7, 0xe3,
	0x29, 0x71, 0x8c, 0x2a, 0x5a, 0xcc, 0x96, 0x8f, 0xc4, 0xdd, 0x34, 0xcc, 0x45, 0xf7, 0xdf, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xef, 0x5d, 0xd8, 0x53, 0xcc, 0x01, 0x00, 0x00,
}
