// Code generated by protoc-gen-go. DO NOT EDIT.
// source: document.proto

package omniscience

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Document struct {
	Id                   *DocumentId          `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Title                string               `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Description          string               `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	Content              string               `protobuf:"bytes,4,opt,name=content" json:"content,omitempty"`
	Url                  string               `protobuf:"bytes,5,opt,name=url" json:"url,omitempty"`
	Service              string               `protobuf:"bytes,6,opt,name=service" json:"service,omitempty"`
	LastModified         *timestamp.Timestamp `protobuf:"bytes,7,opt,name=last_modified,json=lastModified" json:"last_modified,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Document) Reset()         { *m = Document{} }
func (m *Document) String() string { return proto.CompactTextString(m) }
func (*Document) ProtoMessage()    {}
func (*Document) Descriptor() ([]byte, []int) {
	return fileDescriptor_document_d7c48693124db05a, []int{0}
}
func (m *Document) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Document.Unmarshal(m, b)
}
func (m *Document) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Document.Marshal(b, m, deterministic)
}
func (dst *Document) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Document.Merge(dst, src)
}
func (m *Document) XXX_Size() int {
	return xxx_messageInfo_Document.Size(m)
}
func (m *Document) XXX_DiscardUnknown() {
	xxx_messageInfo_Document.DiscardUnknown(m)
}

var xxx_messageInfo_Document proto.InternalMessageInfo

func (m *Document) GetId() *DocumentId {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Document) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Document) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Document) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Document) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Document) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *Document) GetLastModified() *timestamp.Timestamp {
	if m != nil {
		return m.LastModified
	}
	return nil
}

type DocumentId struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DocumentId) Reset()         { *m = DocumentId{} }
func (m *DocumentId) String() string { return proto.CompactTextString(m) }
func (*DocumentId) ProtoMessage()    {}
func (*DocumentId) Descriptor() ([]byte, []int) {
	return fileDescriptor_document_d7c48693124db05a, []int{1}
}
func (m *DocumentId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DocumentId.Unmarshal(m, b)
}
func (m *DocumentId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DocumentId.Marshal(b, m, deterministic)
}
func (dst *DocumentId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DocumentId.Merge(dst, src)
}
func (m *DocumentId) XXX_Size() int {
	return xxx_messageInfo_DocumentId.Size(m)
}
func (m *DocumentId) XXX_DiscardUnknown() {
	xxx_messageInfo_DocumentId.DiscardUnknown(m)
}

var xxx_messageInfo_DocumentId proto.InternalMessageInfo

func (m *DocumentId) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*Document)(nil), "omniscience.Document")
	proto.RegisterType((*DocumentId)(nil), "omniscience.DocumentId")
}

func init() { proto.RegisterFile("document.proto", fileDescriptor_document_d7c48693124db05a) }

var fileDescriptor_document_d7c48693124db05a = []byte{
	// 245 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0x41, 0x4b, 0xf3, 0x40,
	0x10, 0x86, 0x49, 0xfa, 0xb5, 0xfd, 0x3a, 0xd1, 0x22, 0x8b, 0xe0, 0x52, 0x04, 0x43, 0x2f, 0xf6,
	0xb4, 0x05, 0xfd, 0x01, 0x5e, 0xbc, 0x78, 0xf0, 0x12, 0xbc, 0x4b, 0xbb, 0x3b, 0x2d, 0x03, 0xd9,
	0x9d, 0x90, 0x9d, 0xf8, 0xc3, 0xfd, 0x05, 0x92, 0x4d, 0xa2, 0xbd, 0xed, 0x3b, 0xef, 0x33, 0xc3,
	0x3e, 0xb0, 0x76, 0x6c, 0x3b, 0x8f, 0x41, 0x4c, 0xd3, 0xb2, 0xb0, 0x2a, 0xd8, 0x07, 0x8a, 0x96,
	0x30, 0x58, 0xdc, 0x3c, 0x9c, 0x99, 0xcf, 0x35, 0xee, 0x53, 0x75, 0xec, 0x4e, 0x7b, 0x21, 0x8f,
	0x51, 0x0e, 0xbe, 0x19, 0xe8, 0xed, 0x77, 0x06, 0xff, 0x5f, 0xc7, 0x03, 0xea, 0x11, 0x72, 0x72,
	0x3a, 0x2b, 0xb3, 0x5d, 0xf1, 0x74, 0x67, 0x2e, 0xee, 0x98, 0x09, 0x79, 0x73, 0x55, 0x4e, 0x4e,
	0xdd, 0xc2, 0x5c, 0x48, 0x6a, 0xd4, 0x79, 0x99, 0xed, 0x56, 0xd5, 0x10, 0x54, 0x09, 0x85, 0xc3,
	0x68, 0x5b, 0x6a, 0x84, 0x38, 0xe8, 0x59, 0xea, 0x2e, 0x47, 0x4a, 0xc3, 0xd2, 0x72, 0x10, 0x0c,
	0xa2, 0xff, 0xa5, 0x76, 0x8a, 0xea, 0x06, 0x66, 0x5d, 0x5b, 0xeb, 0x79, 0x9a, 0xf6, 0xcf, 0x9e,
	0x8d, 0xd8, 0x7e, 0x91, 0x45, 0xbd, 0x18, 0xd8, 0x31, 0xaa, 0x17, 0xb8, 0xae, 0x0f, 0x51, 0x3e,
	0x3d, 0x3b, 0x3a, 0x11, 0x3a, 0xbd, 0x4c, 0x3f, 0xde, 0x98, 0x41, 0xd6, 0x4c, 0xb2, 0xe6, 0x63,
	0x92, 0xad, 0xae, 0xfa, 0x85, 0xf7, 0x91, 0xdf, 0xde, 0x03, 0xfc, 0x09, 0xa9, 0xf5, 0xaf, 0xf5,
	0xaa, 0x97, 0x3b, 0x2e, 0xd2, 0xfe, 0xf3, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfb, 0x6d, 0x3a,
	0xd1, 0x59, 0x01, 0x00, 0x00,
}
